version: "2"

services:
  webapp:
    extends:
      service: logging
    volumes: 
    - ${TEMP_PATH}:/tmp
    - thumb:/thumb
    - app:/usr/local/webapp
    - ${LOG_PATH}/tomcat:/usr/local/tomcat/logs
    - ${LOG_PATH}/pmis:/var/log/pmis
    - ${EDMS_PATH}:/edms
    environment:
    - SYSTEM_TIMEZONE
    - JAVA_MAX_SIZE
    - JAVA_OPTS
    - MACHINE_HOST
    - PROJECT_NAME
    - DB_URL
    - DB_PASSWORD
    - DB_USERNAME
    - SAP_CO65070
    - SAP_FI65060
    - NLS_URL
    - NLS_PORT
    - NLS_ND_URL1
    - NLS_ND_URL2
    - SSO_DOMAIN
    - SAP_HR65020
    - SAP_HR65030
    - SAP_CO65010

  httpd:
    image: sangah/nginx-pmis
    extends:
      service: logging
    volumes:
    - app:/var/www

  upload:
    image: sangah/pmis-fileupload
    extends:
      service: logging
    volumes:
    - ${TEMP_PATH}:/tmp
    - ngx:/etc/nginx/www

  php:
    image: php:5.6-fpm
    extends:
      service: logging
    volumes:
    - ngx:/etc/nginx/www

  logging:
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"